name: release

on: workflow_dispatch
          
jobs:
  release:
    uses: datavisyn/github-workflows/.github/workflows/release-source.yml@node16
    secrets: 
      DV_DEVOPS: ${{ secrets.DV_DEVOPS }}
